services:
    mysql:
        image: mysql
        container_name: mysql
        restart: always
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DEV_DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DEV_DB_PASSWORD}
        ports:
            - "3306:3306"
        networks:
            - jjhg-net

    nginx:
        image: nginx
        container_name: nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./lib:/etc/nginx/conf.d
            - ./html:/var/www/certbot # acme-challenge 저장용
            - letsencrypt:/etc/letsencrypt # 인증서
        depends_on:
            - mysql
        networks:
            - jjhg-net

    redis:
        image: redis
        container_name: redis
        restart: always
        command: redis-server --requirepass ${DEV_REDIS_PASSWORD}
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        networks:
            - jjhg-net

networks:
    jjhg-net:
        name: jjhg-net
        driver: bridge

volumes:
    mysql-data:
    redis-data:
    letsencrypt:
