# dev 환경용 설정
spring:
  # Swagger 설정
  springdoc:
    swagger-ui:
      path: /docs

  # redis 설정
  data:
    redis:
      contract-invite: ${DEV_REDIS_INVITE_KEY}
      contract-supervisors: ${DEV_REDIS_SUPERVISORS_KEY}
      host: ${DEV_REDIS_HOST}
      port: ${DEV_REDIS_PORT}
      password: ${DEV_REDIS_PASSWORD}

  # MySQL Connection 정보
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 소셜 로그인 Secret
oauth2:
  kakao:
    client-id: ${DEV_OAUTH_KAKAO_CLIENT_ID}
    client-secret: ${DEV_OAUTH_KAKAO_CLIENT_SECRET}

  naver:
    client-id: ${DEV_OAUTH_NAVER_CLIENT_ID}
    client-secret: ${DEV_OAUTH_NAVER_CLIENT_SECRET}

# JWT Secret
jwt:
  secret: ${DEV_JWT_SECRET_KEY}
  access-token-expiration: ${DEV_JWT_ACCESS_EXPIRATION}
  refresh-token-expiration: ${DEV_JWT_REFRESH_EXPIRATION}

# 초대 링크 설정값
invite:
  expired-time: 24
  max-supervisors: 5
  invite-url-prefix: ${DEV_INVITE_URL_PREFIX}


# 클라우드
cloud:
  # AWS
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_S3_BUCKET_DEV}