name: dev-cd
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: 도커 이미지 빌드 및 GHCR 푸시
    runs-on: ubuntu-latest

    steps:
      - name: 브랜치로 체크아웃
        uses: actions/checkout@v4

      - name: GHCR 로그인
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 소문자 이미지 이름 설정
        run: echo "IMAGE_NAME=ghcr.io/prgrms-web-devcourse-final-project/jjhg-api-dev" >> $GITHUB_ENV

      - name: Docker 이미지 빌드 및 푸시
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
